refresh_rate: 5 seconds

appenders:

  console:
    kind: console
    encoder:
      pattern: "{d(%+)(local)} {h({l})} [{T}] {h({f}:{L})} - {m}{n}"
  error:
    kind: rolling_file
    path: "log/error.log"
    append: true
    encoder:
      pattern: "{d(%+)(local)} [{t}] {l} {M}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 2 mb
      roller:
        kind: delete

root:
  level: debug
  appenders:
    - console
    - error
# loggers:
#   app::backend::db:
#     level: info
#   main:
#     level: info
#     appenders:
#       - requests
#     additive: false