refresh_rate: 5 seconds

appenders:
  console:
    kind: console
    encoder:
      pattern: "{d(%+)(local)} [{t}] {h({l})} {M}: {m}{n}"
  error:
    kind: file
    path: "log/error.log"
    encoder:
      pattern: "{d} [{t}] {l} {M}: {m}{n}"

root:
  level: info
  appenders:
    - console
    - error
# loggers:
#   app::backend::db:
#     level: info
#   main:
#     level: info
#     appenders:
#       - requests
#     additive: false